#!/usr/bin/env ruby

# Get all files in out directory
FILES = %w[gitconfig gitignore_global oh-my-zsh rspec tmux tmux.conf vim vimrc zshrc]
DOTFILE_PATH = Dir.pwd
puts ".dotfile is at #{DOTFILE_PATH}..."
puts "initialising submodules..."
`git submodule update --init --recursive`

puts "symlinking dotfiles..."
FILES.each do |file|
    puts "Linking: $HOME/.#{file} -> #{DOTFILE_PATH}/#{file}"
    `ln -ns #{DOTFILE_PATH}/#{file} $HOME/.#{file}`
end

`mkdir -p $HOME/tmp`
puts "DONE."
