COLOUR_BLACK="30"
COLOUR_BLACK_BG="40"
COLOUR_RED_BG="41"
COLOUR_RED="31"
COLOUR_GREEN="32"
COLOUR_GREEN_BG="42"
COLOUR_YELLOW="33"
COLOUR_YELLOW_BG="43"
COLOUR_BLUE="34"
COLOUR_BLUE_BG="44"
COLOUR_MAGENTA="35"
COLOUR_MAGENTA_BG="45"
COLOUR_CYAN="36"
COLOUR_CYAN_BG="46"
COLOUR_LIGHT_GRAY="37"
COLOUR_LIGHT_GRAY_BG="47"
COLOUR_GRAY="90"
COLOUR_GRAY_BG="100"
COLOUR_LIGHT_RED="91"
COLOUR_LIGHT_RED_BG="101"
COLOUR_LIGHT_GREEN="92"
COLOUR_LIGHT_GREEN_BG="102"
COLOUR_LIGHT_YELLOW="93"
COLOUR_LIGHT_YELLOW_BG="103"
COLOUR_LIGHT_BLUE="94"
COLOUR_LIGHT_BLUE_BG="104"
COLOUR_LIGHT_MAGENTA="95"
COLOUR_LIGHT_MAGENTA_BG="105"
COLOUR_LIGHT_CYAN="96"
COLOUR_LIGHT_CYAN_BG="106"
COLOUR_WHITE="97"
COLOUR_WHITE_BG="107"

function colour_set() {
  printf "\e[${1}m"
}

function colour_reset() {
  printf "\e[0m"
}

function colour_bold() {
  printf "\e[1m"
}

function colour_faint() {
  printf "\e[2m"
}

function colour_italic() {
  printf "\e[3m"
}

function colour_underline() {
  printf "\e[4m"
}
